### PR TITLE
Pkg dev - defensive programming - fix slug invasion

### PR DESCRIPTION
**Pull request by aappling-usgs**

### CODE REVIEW

**Comment by aappling-usgs** [comment]
ohhh, THAT'S what that was for! =)

**Comment by lindsaycarr** [comment]
@aappling-usgs I think your date is `09-30` not `07-31`? 

https://github.com/USGS-R/training-curriculum/issues/154

**Comment by lindsaycarr** [comment]
I gave each lesson a specific date in the issue so that they would end up in the correct order :) Documentation #156 already has `07-31`

**Comment by aappling-usgs** [comment]
ugh. i went to the wrong issue to find my date, sorry

**Pull request merged**
