### PR TITLE
remove smwr and gsIntroR package installs + add geoknife

### PR DESCRIPTION
**Pull request by lindsaycarr**
@jiwalker-usgs should we actually do this?

### CODE REVIEW

**Comment by jiwalker-usgs** [comment]
I don't see any harm in this, though it depends on if this list is meant to be the minimum set of packages we require for training, or a list of packages that might be of use.

**Comment by lindsaycarr** [comment]
hmm I'd say what we think might be useful to people + what is needed for the course

**Comment by wdwatkins** [comment]
Don't we want to discourage use of the smwr packages anyways?  Or are there not viable replacements yet?

**Comment by aappling-usgs** [comment]
there are viable replacements for everything we show students in the course...my vote is for removing the smwrs from the curriculum prep

**Comment by jiwalker-usgs** [comment]
This is more about including geoknife, we don't use smwr in the course, so it can be safely removed.

**Comment by jread-usgs** [comment]
@wdwatkins and I think the point is to discourage the use of packages that are unmaintained and unsupported.

**Pull request merged**
