### PR TITLE
image name was wrong case

### PR DESCRIPTION
**Pull request by wdwatkins**

### CODE REVIEW

**Comment by lindsaycarr** [comment]
those were actually saved with .PNG, so you need to change the file, too

https://github.com/USGS-R/training-curriculum/blob/master/content/r-package-dev/static/img/merge_conflict_code.PNG

**Comment by lindsaycarr** [comment]
there are two of instances: 

`merge_conflict_code.PNG`
`merge_conflict_git_tab.PNG`

**Comment by wdwatkins** [comment]
It's `merge_conflict_shell.png` though, those other two are fine.

**Comment by lindsaycarr** [comment]
ohhhhhhhh sorry!

**Pull request merged**
