### PR TITLE
Outline for Maintenance

### PR DESCRIPTION
**Pull request by jread-usgs**
Mostly outline only, but I think this is a decent start for the scope of this module. 

Anything I left out that should be in? Anything I included that probably isn't worth the time/space?

I will be adding prose/examples in the future.

### CODE REVIEW

**Comment by lindsaycarr** [comment]
:tada: I can't take a look now, but will review later :)

@jread-usgs for objectives, I listed them in the issue description #157. Those were objectives we came up with together when creating that course document.

**Comment by jread-usgs** [comment]
Great, I can fit most of those:
2. Organize tasks on GitHub in Milestones and Projects.
3. Reference tasks in GitHub Pull Requests and Issues. 
4. Use reviewer requests on GitHub.
5. Describe process to update packages on GRAN.
in the `Maintaining your R package` section

**Comment by lindsaycarr** [comment]
@jread-usgs any particular reason not for doing the first one?

**Comment by jread-usgs** [comment]
I was thin thinking that item would fit better in the `Level of support` section

**Comment by ldecicco-USGS** [comment]
I'm going to merge this so we can start to get a feel for how things are flowing on the site. Feel free to add more text!

**Comment by lindsaycarr** [comment]
Finally had a chance to read through this!

- I really like the common pitfalls in each section; I will personally benefit from reviewing those. 
- And :+1: on "How to gracefully throw in the towell"!
- When we start to add content to this, just keep in mind that some of these seem related to @aappling-usgs's suggestions in #154 and we should point to them when applicable.

**Pull request merged**
