### PR TITLE
Toggle button [TEST - don't merge!]

### PR DESCRIPTION
**Pull request by lindsaycarr**

### CODE REVIEW

**Comment by lindsaycarr** [comment]
@mwernimont any idea why I can't get the button to look like a button?

image

It looks good in this blog post: https://github.com/USGS-OWI/owi-blog/blob/a7eb5a3b536d1dd58b52f65c5342421e37c25261/content/accessLOCAwithR.Rmd

**Comment by mwernimont** [comment]
@lindsaycarr From what I can see you have the button as a div instead of a <button></button> which comes with browser default CSS to look like a button.  You can use the div, but you have to do your own CSS to make it look like a button.

**Comment by lindsaycarr** [comment]
@mwernimont it doesn't render on that page, but that's where you can see the code for creating it. Here's what it actually looks like: 

image

Thought I followed everything that was done for this, but I'll try just using `<button></button>`

**Comment by mwernimont** [comment]
So I'm confused if it looks like a button on the blog what's the issue?  Isn't the end goal?

**Comment by lindsaycarr** [comment]
Yes, but for some reason what I've added here (even though I've tried to follow the exact same steps) does not result in what is on the blog. I was hoping you would be able to catch the thing I'm missing :)

Though, the `<button>` thing is easier to work with and might do the trick.

**Comment by lindsaycarr** [comment]
@ldecicco-USGS the button is working!

@mwernimont any idea why the second button is toggling the first code chunk? Does their need to be a unique id for each?

**Comment by lindsaycarr** [comment]
Buttons are working appropriately now! I'm going to close this PR so that we will have the .Rmd as an example for when we need to add buttons for the assessments, but will open a new PR just committing the function `toggle_visibility`. 

To add buttons, the `.Rmd` will need this in the setup code chunk (L30-37):
```r
knit_hooks$set(addToggle = function(before, options, envir) {
    if(before) {
      sprintf('<button class="ToggleButton" onclick="toggle_visibility(\'%1$s\')">Show Answer</button>
              <div id="%1$s" style="display:none">', opts_current$get('label'))
    } else {
      '</div>'
    }
})
```
and each code chunk that wants a button needs to have `addToggle='ON'` in the chunk options. FYI, the value supplied to `addToggle` could be anything - it just allows the function named `addToggle` to actually get called. I chose `ON` since it would make the most sense.

**Pull request closed without merging**
