### PR TITLE
base origin url

### PR DESCRIPTION
**Pull request by mwernimont**
@lindsaycarr Can you test to see if this works?

### CODE REVIEW

**Comment by lindsaycarr** [comment]
the link for "Course Specific Materials" drop down and the basic "Training" tab are not working on my local version

**Comment by lindsaycarr** [comment]
for the "Training" tab it looks like it is trying to take me to /R/training rather than "/R/training.html", but the code says otherwise

**Comment by lindsaycarr** [comment]
OH - for course-specific it is `course-specific-material`, not `course-specific-links`. That is why that one's broken. Still not sure about the basic training tab

**Comment by mwernimont** [comment]
Hmmm...my training tab seems to be working fine. You getting a 404?

**Comment by lindsaycarr** [comment]
Oh it's because it switches over to owi.usgs.gov rather than the local host at that point, and it is broken there. But I've got a PR in to fix that: https://github.com/USGS-R/usgs-r-website/pull/128. So everything should be working once both of these are merged. I'll merge this one - can you merge the usgs-r-website one?

**Pull request merged**
