### PR TITLE
code styling for intro

### PR DESCRIPTION
**Pull request by mwernimont**
@ldecicco-USGS Did you want the squares to be smaller too?

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
Yeah, I think so. @lindsaycarr , agree?

**Comment by lindsaycarr** [comment]
@mwernimont do you mean the code blocks would be less than the width of the rest?

**Comment by ldecicco-USGS** [comment]
He took out the whitespace in the bottom of the "notecards" for the blogs. I think the same issue is in the training too....

**Comment by lindsaycarr** [comment]
Oh yeah, let's do that

**Pull request merged**
