### PR TITLE
What's a package?

### PR DESCRIPTION
**Pull request by ldecicco-USGS**
Starting work on the "package mechanics" section, but will happily take comments on the "What's a Package" section.

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
Okey dokey, that's all I've got time for for a few days. I think it's complete enough for people to review. There's PLENTY of room for edits. I consider this a first pass of many.....

**Comment by ldecicco-USGS** [comment]
I'm going to push this up to dev so you guys can all have a look there.

**Comment by lindsaycarr** [comment]
#152

**Comment by lindsaycarr** [comment]
and #185

**Pull request merged**
