### PR TITLE
accordion sidebar options

### PR DESCRIPTION
**Pull request by mwernimont**
@lindsaycarr Sorry for the long time it took for this, teaching myself proper jquery traversing took longer than I expected, but it seemed to work out just fine. The menus with children now expand and collapse when you click on the plus or minus. 

anything like you envisioned?

### CODE REVIEW

**Comment by lindsaycarr** [comment]
hmmm I'm running this locally but I don't see any of the changes

**Comment by lindsaycarr** [comment]
Hmm code is there - not sure. Looked good on your screen though!

**Comment by mwernimont** [comment]
@lindsaycarr After you merged it is still not there?

**Comment by mwernimont** [comment]
404 error for the images...I'll fix and get a PR for it

**Pull request merged**
