### PR TITLE
add generic version control diagram

### PR DESCRIPTION
**Pull request by lindsaycarr**
@ldecicco-USGS @limnoliver @wdwatkins how does this diagram look? I added a paragraph describing it, and included the image file.

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
yeah, looks good. You'll have both, right?

**Comment by limnoliver** [comment]
@lindsaycarr I like it! To show the advantage of the users' personal online repository, you could show another arrow to one of the user's repositories and have two computers (maybe work and home, or desktop and laptop). Not essential but might help conceptualize why you need the cloud version of your work.

**Comment by lindsaycarr** [comment]
@ldecicco-USGS yes the other is linked farther down after we introduce all of the terms.

Hmmm @limnoliver that's an interesting suggestion. Let me play around with that and see what I come up with.

**Comment by lindsaycarr** [comment]
@limnoliver what do you think? Too busy?

github_workflow_diagram_2local

**Comment by lindsaycarr** [comment]
Wait, how about this one instead?

github_workflow_diagram_2local_v2

**Comment by limnoliver** [comment]
I really like it. I think it more accurately encompasses how people interface with a project.

**Comment by limnoliver** [comment]
And yes, I like the double arrows.

**Comment by lindsaycarr** [comment]
Should I put double arrows on the other side, too? Just noticed I don't have them for User 2

**Comment by limnoliver** [comment]
Yeah, I think so, to show it's a "backup" of your local version.

**Pull request merged**
